export enum SheetName {
  USERS = 'User',
  QUOTAS = 'Quota',
  FIELDS = 'Field',
  TERMS = 'Dot',
  REGISTRATIONS = 'Registrations',
  COMMITTEES = 'Committees',
  SCORES = 'Diem',
  STUDENT_DOCUMENTS = 'Linkbainop',
  LECTURER_DOCUMENTS = 'LinkGiangvien',
  SUGGESTED_TOPICS = 'Detaigoiy',
  NOTIFICATIONS = 'Notifications',
  MINUTES = 'Minutes',
  REGISTRATION_WORKFLOW_STATUSES = 'RegistrationWorkflowStatuses',
  REGISTRATION_STATUS_HISTORY = 'RegistrationStatusHistory',
}

export const REQUIRED_SHEET_HEADERS: Record<SheetName, string[]> = {
  [SheetName.USERS]: [
    'id',
    'email',
    'password',
    'ms',
    'ten',
    'role',
    'createdAt',
  ],
  [SheetName.QUOTAS]: [
    'id',
    'emailGV',
    'msgv',
    'quota',
    'usedSlots',
    'heDaoTao',
    'dot',
    'status',
    'approvedAt',
  ],
  [SheetName.FIELDS]: ['id', 'emailGV', 'fieldName'],
  [SheetName.TERMS]: [
    'id',
    'tenDot',
    'loai',
    'namHoc',
    'hocKy',
    'registrationOpenAt',
    'registrationCloseAt',
    'submissionOpenAt',
    'submissionCloseAt',
    'defenseDate',
    'isActive',
  ],
  [SheetName.REGISTRATIONS]: [
    'id',
    'emailSV',
    'tenSV',
    'loai',
    'tenDeTai',
    'linhVuc',
    'tenCongTy',
    'emailGVHD',
    'emailGVPB',
    'dot',
    'status',
    'committeeId',
    'defenseDate',
    'location',
    'finalScore',
    'supervisorApproved',
    'chairApproved',
    'rejectionReason',
    'createdAt',
    'updatedAt',
  ],
  [SheetName.COMMITTEES]: [
    'id',
    'committeeName',
    'dot',
    'chairEmail',
    'secretaryEmail',
    'member1Email',
    'member2Email',
    'location',
    'defenseDate',
    'createdAt',
  ],
  [SheetName.SCORES]: [
    'id',
    'registrationId',
    'emailGV',
    'vaiTroCham',
    'score1',
    'score2',
    'score3',
    'totalScore',
    'comments',
    'questions',
    'createdAt',
    'updatedAt',
  ],
  [SheetName.STUDENT_DOCUMENTS]: [
    'id',
    'registrationId',
    'emailSV',
    'documentType',
    'fileName',
    'fileUrl',
    'uploadedAt',
  ],
  [SheetName.LECTURER_DOCUMENTS]: [
    'id',
    'registrationId',
    'emailGV',
    'documentType',
    'fileName',
    'fileUrl',
    'uploadedAt',
  ],
  [SheetName.SUGGESTED_TOPICS]: [
    'id',
    'title',
    'fieldName',
    'emailGV',
    'description',
    'status',
    'createdAt',
  ],
  [SheetName.NOTIFICATIONS]: [
    'id',
    'receiverEmail',
    'title',
    'content',
    'type',
    'referenceId',
    'isRead',
    'createdAt',
  ],
  [SheetName.MINUTES]: [
    'id',
    'registrationId',
    'generatedBy',
    'content',
    'fileUrl',
    'createdAt',
    'updatedAt',
  ],
  [SheetName.REGISTRATION_WORKFLOW_STATUSES]: [
    'id',
    'loai',
    'status',
    'label',
    'description',
    'step',
    'stepLabel',
    'actor',
    'color',
    'nextStatuses',
    'canStudentUpdate',
    'canLecturerUpdate',
    'canManagerUpdate',
    'isTerminal',
    'sortOrder',
  ],
  [SheetName.REGISTRATION_STATUS_HISTORY]: [
    'id',
    'registrationId',
    'status',
    'statusLabel',
    'changedBy',
    'changedByRole',
    'note',
    'changedAt',
  ],
};
