export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  FORBIDDEN_ROLE = 'FORBIDDEN_ROLE',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  TERM_NOT_OPEN = 'TERM_NOT_OPEN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  REGISTRATION_NOT_FOUND = 'REGISTRATION_NOT_FOUND',
  DOCUMENT_NOT_ALLOWED = 'DOCUMENT_NOT_ALLOWED',
  SCORE_NOT_ALLOWED = 'SCORE_NOT_ALLOWED',
  COMMITTEE_ASSIGNMENT_INVALID = 'COMMITTEE_ASSIGNMENT_INVALID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
}
