export enum LecturerBusinessRole {
  SUPERVISOR = 'SUPERVISOR',
  REVIEWER = 'REVIEWER',
  COMMITTEE_MEMBER = 'COMMITTEE_MEMBER',
  COMMITTEE_CHAIR = 'COMMITTEE_CHAIR',
  COMMITTEE_SECRETARY = 'COMMITTEE_SECRETARY',
}
